In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

import pickle
import warnings

warnings.filterwarnings('ignore')

In [2]:
data = pd.read_excel('white_list CC_202403_Area Jkt Gambir.xlsx')
data

employer_company_name      hp_final   cif_number  \
0                         MIC MAC PELAYAN TOKO  6.282268e+12  23001084780   
1                         TOKO SAHABAT   OWNER  6.288200e+11  20001228880   
2        PT  INTEGRA LINE INDONESIA ACCOUNTING  6.285715e+12  20001219835   
3       MARITIME POWER PT CREW PELAYARAN KAPAL  6.282184e+12  19005643150   
4                           USAHA RENTAL MOBIL  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        PT  ECOM MULTI SOLUTION   IT SALES  6.282122e+12   3000500265   
2509                       MAJU LANCAR MEKANIK  6.281298e+11   2000851724   
2510                   PT Jhonlin Marine Trans  6.281386e+12   1001899658   
2511  PT METROPOLITAN LAND MANAGER ENGINEERING  6.281282e+12   1001771517   
2512  KPP Pratama Jakarta Sawah Besar Satu Sek  6.281231e+12  25001737907   

                       fullname flag_vip gender product_offer_1  \
0                 WENDY PRAYOGO        N      M          BMVPLB   
1                HONEST SASWITA        N      M          PGGCTB   
2                TINI SUHARTINI        N      F          PGGCTB   
3                         SANUI        N      M          BMVPLB   
4               SOETIRTO TAMZIL        N      M          BMVPLB   
...                         ...      ...    ...             ...   
2508           CHANDRA MULIANDI        N      M          BMVPLB   
2509             BAMBANG SADONO        N      M          PGGCTB   
2510       AVIA HILMANSJAH NOOR        N      M          BMVPLB   
2511                  ANTO BARA        N      M          PGGCTB   
2512  YOESTANIA PRATAMI HIDAYAT        N      F          PGGCTB   

     product_offer_2 product_offer_3 product_offer_4  indicative_limit  \
0             SIGNPB          MSHPEB          SIGLFB      8.795173e+07   
1             BMVPLB          MSHPEB          JPRECB      1.703737e+07   
2             BMVPLB          MSHPEB          JPRECB      1.948948e+07   
3             SIGNPB          MSHPEB          SIGLFB      4.233099e+07   
4             SIGNPB          MSHPEB          SIGLFB      9.130256e+07   
...              ...             ...             ...               ...   
2508          SIGNPB          MSHPEB          SIGLFB      1.500000e+08   
2509          BMVPLB          MSHPEB          JPRECB      2.324598e+07   
2510          SIGNPB          MSHPEB          SIGLFB      5.082298e+07   
2511          BMVPLB          MSHPEB          JPRECB      2.576513e+07   
2512          BMVPLB          MSHPEB          JPRECB      1.751294e+07   

     segment  flag_staff  branch_bds          hub_nm         status  \
0        ETB           0       11934  JAKARTA GAMBIR  Not Apply Yet   
1        ETB           0       11929  JAKARTA GAMBIR  Not Apply Yet   
2        ETB           0       11916  JAKARTA GAMBIR  Not Apply Yet   
3        ETB           0       11936  JAKARTA GAMBIR  Not Apply Yet   
4        ETB           0       11937  JAKARTA GAMBIR  Not Apply Yet   
...      ...         ...         ...             ...            ...   
2508     ETB           0       11931  JAKARTA GAMBIR  Not Apply Yet   
2509     ETB           0       11923  JAKARTA GAMBIR  Not Apply Yet   
2510     ETB           0       11903  JAKARTA GAMBIR  Not Apply Yet   
2511     ETB           0       11923  JAKARTA GAMBIR  Not Apply Yet   
2512     ETB           0       11900  JAKARTA GAMBIR  Not Apply Yet   

     ureg_status flg_segment_perusahaan  
0           UREG                    NaN  
1           UREG                    NaN  
2           UREG                    NaN  
3           UREG                    NaN  
4           UREG                    NaN  
...          ...                    ...  
2508        UREG                    NaN  
2509        UREG                    NaN  
2510        UREG                    NaN  
2511        UREG                    NaN  
2512        UREG                    NaN  

[2513 rows x 18 columns]

In [3]:
data.dtypes

employer_company_name      object
hp_final                  float64
cif_number                  int64
fullname                   object
flag_vip                   object
gender                     object
product_offer_1            object
product_offer_2            object
product_offer_3            object
product_offer_4            object
indicative_limit          float64
segment                    object
flag_staff                  int64
branch_bds                  int64
hub_nm                     object
status                     object
ureg_status                object
flg_segment_perusahaan     object
dtype: object

In [4]:
len(data)

2513

In [5]:
data['ureg_status'] = data['ureg_status'].replace({'NON UREG': 0, 'UREG': 1})

In [6]:
len(data)

2513

In [7]:
data

employer_company_name      hp_final   cif_number  \
0                         MIC MAC PELAYAN TOKO  6.282268e+12  23001084780   
1                         TOKO SAHABAT   OWNER  6.288200e+11  20001228880   
2        PT  INTEGRA LINE INDONESIA ACCOUNTING  6.285715e+12  20001219835   
3       MARITIME POWER PT CREW PELAYARAN KAPAL  6.282184e+12  19005643150   
4                           USAHA RENTAL MOBIL  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        PT  ECOM MULTI SOLUTION   IT SALES  6.282122e+12   3000500265   
2509                       MAJU LANCAR MEKANIK  6.281298e+11   2000851724   
2510                   PT Jhonlin Marine Trans  6.281386e+12   1001899658   
2511  PT METROPOLITAN LAND MANAGER ENGINEERING  6.281282e+12   1001771517   
2512  KPP Pratama Jakarta Sawah Besar Satu Sek  6.281231e+12  25001737907   

                       fullname flag_vip gender product_offer_1  \
0                 WENDY PRAYOGO        N      M          BMVPLB   
1                HONEST SASWITA        N      M          PGGCTB   
2                TINI SUHARTINI        N      F          PGGCTB   
3                         SANUI        N      M          BMVPLB   
4               SOETIRTO TAMZIL        N      M          BMVPLB   
...                         ...      ...    ...             ...   
2508           CHANDRA MULIANDI        N      M          BMVPLB   
2509             BAMBANG SADONO        N      M          PGGCTB   
2510       AVIA HILMANSJAH NOOR        N      M          BMVPLB   
2511                  ANTO BARA        N      M          PGGCTB   
2512  YOESTANIA PRATAMI HIDAYAT        N      F          PGGCTB   

     product_offer_2 product_offer_3 product_offer_4  indicative_limit  \
0             SIGNPB          MSHPEB          SIGLFB      8.795173e+07   
1             BMVPLB          MSHPEB          JPRECB      1.703737e+07   
2             BMVPLB          MSHPEB          JPRECB      1.948948e+07   
3             SIGNPB          MSHPEB          SIGLFB      4.233099e+07   
4             SIGNPB          MSHPEB          SIGLFB      9.130256e+07   
...              ...             ...             ...               ...   
2508          SIGNPB          MSHPEB          SIGLFB      1.500000e+08   
2509          BMVPLB          MSHPEB          JPRECB      2.324598e+07   
2510          SIGNPB          MSHPEB          SIGLFB      5.082298e+07   
2511          BMVPLB          MSHPEB          JPRECB      2.576513e+07   
2512          BMVPLB          MSHPEB          JPRECB      1.751294e+07   

     segment  flag_staff  branch_bds          hub_nm         status  \
0        ETB           0       11934  JAKARTA GAMBIR  Not Apply Yet   
1        ETB           0       11929  JAKARTA GAMBIR  Not Apply Yet   
2        ETB           0       11916  JAKARTA GAMBIR  Not Apply Yet   
3        ETB           0       11936  JAKARTA GAMBIR  Not Apply Yet   
4        ETB           0       11937  JAKARTA GAMBIR  Not Apply Yet   
...      ...         ...         ...             ...            ...   
2508     ETB           0       11931  JAKARTA GAMBIR  Not Apply Yet   
2509     ETB           0       11923  JAKARTA GAMBIR  Not Apply Yet   
2510     ETB           0       11903  JAKARTA GAMBIR  Not Apply Yet   
2511     ETB           0       11923  JAKARTA GAMBIR  Not Apply Yet   
2512     ETB           0       11900  JAKARTA GAMBIR  Not Apply Yet   

      ureg_status flg_segment_perusahaan  
0               1                    NaN  
1               1                    NaN  
2               1                    NaN  
3               1                    NaN  
4               1                    NaN  
...           ...                    ...  
2508            1                    NaN  
2509            1                    NaN  
2510            1                    NaN  
2511            1                    NaN  
2512            1                    NaN  

[2513 rows x 18 columns]

In [8]:
len(data[data['ureg_status']==0])

495

In [9]:
data_fix = data[data['ureg_status']==1]
data_fix['employer_company_name'] = data_fix['employer_company_name'].str.lower()
data_fix

employer_company_name      hp_final   cif_number  \
0                         mic mac pelayan toko  6.282268e+12  23001084780   
1                         toko sahabat   owner  6.288200e+11  20001228880   
2        pt  integra line indonesia accounting  6.285715e+12  20001219835   
3       maritime power pt crew pelayaran kapal  6.282184e+12  19005643150   
4                           usaha rental mobil  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        pt  ecom multi solution   it sales  6.282122e+12   3000500265   
2509                       maju lancar mekanik  6.281298e+11   2000851724   
2510                   pt jhonlin marine trans  6.281386e+12   1001899658   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   
2512  kpp pratama jakarta sawah besar satu sek  6.281231e+12  25001737907   

                       fullname flag_vip gender product_offer_1  \
0                 WENDY PRAYOGO        N      M          BMVPLB   
1                HONEST SASWITA        N      M          PGGCTB   
2                TINI SUHARTINI        N      F          PGGCTB   
3                         SANUI        N      M          BMVPLB   
4               SOETIRTO TAMZIL        N      M          BMVPLB   
...                         ...      ...    ...             ...   
2508           CHANDRA MULIANDI        N      M          BMVPLB   
2509             BAMBANG SADONO        N      M          PGGCTB   
2510       AVIA HILMANSJAH NOOR        N      M          BMVPLB   
2511                  ANTO BARA        N      M          PGGCTB   
2512  YOESTANIA PRATAMI HIDAYAT        N      F          PGGCTB   

     product_offer_2 product_offer_3 product_offer_4  indicative_limit  \
0             SIGNPB          MSHPEB          SIGLFB      8.795173e+07   
1             BMVPLB          MSHPEB          JPRECB      1.703737e+07   
2             BMVPLB          MSHPEB          JPRECB      1.948948e+07   
3             SIGNPB          MSHPEB          SIGLFB      4.233099e+07   
4             SIGNPB          MSHPEB          SIGLFB      9.130256e+07   
...              ...             ...             ...               ...   
2508          SIGNPB          MSHPEB          SIGLFB      1.500000e+08   
2509          BMVPLB          MSHPEB          JPRECB      2.324598e+07   
2510          SIGNPB          MSHPEB          SIGLFB      5.082298e+07   
2511          BMVPLB          MSHPEB          JPRECB      2.576513e+07   
2512          BMVPLB          MSHPEB          JPRECB      1.751294e+07   

     segment  flag_staff  branch_bds          hub_nm         status  \
0        ETB           0       11934  JAKARTA GAMBIR  Not Apply Yet   
1        ETB           0       11929  JAKARTA GAMBIR  Not Apply Yet   
2        ETB           0       11916  JAKARTA GAMBIR  Not Apply Yet   
3        ETB           0       11936  JAKARTA GAMBIR  Not Apply Yet   
4        ETB           0       11937  JAKARTA GAMBIR  Not Apply Yet   
...      ...         ...         ...             ...            ...   
2508     ETB           0       11931  JAKARTA GAMBIR  Not Apply Yet   
2509     ETB           0       11923  JAKARTA GAMBIR  Not Apply Yet   
2510     ETB           0       11903  JAKARTA GAMBIR  Not Apply Yet   
2511     ETB           0       11923  JAKARTA GAMBIR  Not Apply Yet   
2512     ETB           0       11900  JAKARTA GAMBIR  Not Apply Yet   

      ureg_status flg_segment_perusahaan  
0               1                    NaN  
1               1                    NaN  
2               1                    NaN  
3               1                    NaN  
4               1                    NaN  
...           ...                    ...  
2508            1                    NaN  
2509            1                    NaN  
2510            1                    NaN  
2511            1                    NaN  
2512            1                    NaN  

[2018 rows x 18 columns]

In [10]:
len(data_fix)

2018

### Type clustering
1. PT (berarti memiliki penghasilan tetap)
2. Wirausaha/Pemilik Usaha (hint kata "wirausaha"/"manager level")
3. Perseorangan/Kerja tidak dibawah PT

In [11]:
data_fix = data_fix.drop_duplicates()
data_fix = data_fix.drop(columns=['flag_vip', 'gender', 'product_offer_1', 'product_offer_2', 'product_offer_3', 'product_offer_4',
                                 'segment','status', 'flg_segment_perusahaan', 'flag_staff'])
data_fix

employer_company_name      hp_final   cif_number  \
0                         mic mac pelayan toko  6.282268e+12  23001084780   
1                         toko sahabat   owner  6.288200e+11  20001228880   
2        pt  integra line indonesia accounting  6.285715e+12  20001219835   
3       maritime power pt crew pelayaran kapal  6.282184e+12  19005643150   
4                           usaha rental mobil  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        pt  ecom multi solution   it sales  6.282122e+12   3000500265   
2509                       maju lancar mekanik  6.281298e+11   2000851724   
2510                   pt jhonlin marine trans  6.281386e+12   1001899658   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   
2512  kpp pratama jakarta sawah besar satu sek  6.281231e+12  25001737907   

                       fullname  indicative_limit  branch_bds          hub_nm  \
0                 WENDY PRAYOGO      8.795173e+07       11934  JAKARTA GAMBIR   
1                HONEST SASWITA      1.703737e+07       11929  JAKARTA GAMBIR   
2                TINI SUHARTINI      1.948948e+07       11916  JAKARTA GAMBIR   
3                         SANUI      4.233099e+07       11936  JAKARTA GAMBIR   
4               SOETIRTO TAMZIL      9.130256e+07       11937  JAKARTA GAMBIR   
...                         ...               ...         ...             ...   
2508           CHANDRA MULIANDI      1.500000e+08       11931  JAKARTA GAMBIR   
2509             BAMBANG SADONO      2.324598e+07       11923  JAKARTA GAMBIR   
2510       AVIA HILMANSJAH NOOR      5.082298e+07       11903  JAKARTA GAMBIR   
2511                  ANTO BARA      2.576513e+07       11923  JAKARTA GAMBIR   
2512  YOESTANIA PRATAMI HIDAYAT      1.751294e+07       11900  JAKARTA GAMBIR   

      ureg_status  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
2508            1  
2509            1  
2510            1  
2511            1  
2512            1  

[2006 rows x 8 columns]

In [12]:
data_fix['indicative_limit'] =  data_fix['indicative_limit'].round()
data_fix

employer_company_name      hp_final   cif_number  \
0                         mic mac pelayan toko  6.282268e+12  23001084780   
1                         toko sahabat   owner  6.288200e+11  20001228880   
2        pt  integra line indonesia accounting  6.285715e+12  20001219835   
3       maritime power pt crew pelayaran kapal  6.282184e+12  19005643150   
4                           usaha rental mobil  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        pt  ecom multi solution   it sales  6.282122e+12   3000500265   
2509                       maju lancar mekanik  6.281298e+11   2000851724   
2510                   pt jhonlin marine trans  6.281386e+12   1001899658   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   
2512  kpp pratama jakarta sawah besar satu sek  6.281231e+12  25001737907   

                       fullname  indicative_limit  branch_bds          hub_nm  \
0                 WENDY PRAYOGO        87951727.0       11934  JAKARTA GAMBIR   
1                HONEST SASWITA        17037370.0       11929  JAKARTA GAMBIR   
2                TINI SUHARTINI        19489481.0       11916  JAKARTA GAMBIR   
3                         SANUI        42330985.0       11936  JAKARTA GAMBIR   
4               SOETIRTO TAMZIL        91302562.0       11937  JAKARTA GAMBIR   
...                         ...               ...         ...             ...   
2508           CHANDRA MULIANDI       150000000.0       11931  JAKARTA GAMBIR   
2509             BAMBANG SADONO        23245985.0       11923  JAKARTA GAMBIR   
2510       AVIA HILMANSJAH NOOR        50822983.0       11903  JAKARTA GAMBIR   
2511                  ANTO BARA        25765130.0       11923  JAKARTA GAMBIR   
2512  YOESTANIA PRATAMI HIDAYAT        17512938.0       11900  JAKARTA GAMBIR   

      ureg_status  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
2508            1  
2509            1  
2510            1  
2511            1  
2512            1  

[2006 rows x 8 columns]

Kategori 1 : 'PT', 'Depdagri', 'DITJEN', 'kemenkeu', 'depkeu', 'sd', 'smp', 'sma', 'kementerian', 'kementrian', 'kppn', 'kpp', 'kemendagri', 'polkum', 'kabinet', 'sekretariat', 'negara', 'astra', 'dephub', 'ppatk', 'ojk', 'lembaga', 'departemen', 'unand', 'tk', 'direktorat', 'ykk', 'mahkamah', 'bank', 'dirjen', 'sriwijaya', 'pgn', 'kemenkes', 'dpr', 'brin', 'kimia farma', 'sekneg', 'setjen', 'airnav', 'djp', 'bmkg', 'basarnas', 'sar', 'kejaksaan', 'rs', 'rumah sakit', 'badan', 'askrindo', 'bazarnas', 'airlines', 'air asia', 'komisi', 'walikota', 'tripatra', 'lpmi', 'tni', 'tentara', 'polisi', 'polri', 'indomarco', 'lemhanas', 'dinas', 'telekom', 'telkom', 'arsip', 'bps', 'otoritas', 'pos', 'bea cukai', 'pemda', 'pgas', 'kelurahan', 'kecamatan'

kategori 2 : 'Pemilik', 'manager', 'manajer', 'owner', 'kontrakan', 'kosan'

In [13]:
keywords_1 = ['PT', 'Depdagri', 'DITJEN', 'kemenkeu', 'depkeu', 'sd', 'smp', 'sma', 'kementerian', 'kementrian', 'kppn', 'kpp', 'kemendagri', 'polkum', 'kabinet', 'sekretariat', 'negara', 'astra', 'dephub', 'ppatk', 'ojk', 'lembaga', 'departemen', 'unand', 'tk', 'direktorat', 'ykk', 'mahkamah', 'bank', 'dirjen', 'sriwijaya', 'pgn', 'kemenkes', 'dpr', 'brin', 'kimia farma', 'sekneg', 'setjen', 'airnav', 'djp', 'bmkg', 'basarnas', 'sar', 'kejaksaan', 'rs', 'rumah sakit', 'badan', 'askrindo', 'bazarnas', 'airlines', 'air asia', 'komisi', 'walikota', 'tripatra', 'lpmi', 'tni', 'tentara', 'polisi', 'polri', 'indomarco', 'lemhanas', 'dinas', 'telekom', 'telkom', 'arsip', 'bps', 'otoritas', 'pos', 'bea cukai', 'pemda', 'pgas', 'kelurahan', 'kecamatan']
keywords_1 = [keyword.lower() for keyword in keywords_1]
keywords_2 = ['Pemilik', 'Manager', 'manajer', 'OWNER', 'Kontrakan', 'Kosan']
keywords_2 = [keyword.lower() for keyword in keywords_2]
data_fix['segment_company_pt'] = np.where(data_fix['employer_company_name'].str.contains('|'.join(keywords_1)), 1, 0)
data_fix['segment_company_owner'] = np.where(data_fix['employer_company_name'].str.contains('|'.join(keywords_2)), 1, 0)

data_fix

employer_company_name      hp_final   cif_number  \
0                         mic mac pelayan toko  6.282268e+12  23001084780   
1                         toko sahabat   owner  6.288200e+11  20001228880   
2        pt  integra line indonesia accounting  6.285715e+12  20001219835   
3       maritime power pt crew pelayaran kapal  6.282184e+12  19005643150   
4                           usaha rental mobil  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        pt  ecom multi solution   it sales  6.282122e+12   3000500265   
2509                       maju lancar mekanik  6.281298e+11   2000851724   
2510                   pt jhonlin marine trans  6.281386e+12   1001899658   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   
2512  kpp pratama jakarta sawah besar satu sek  6.281231e+12  25001737907   

                       fullname  indicative_limit  branch_bds          hub_nm  \
0                 WENDY PRAYOGO        87951727.0       11934  JAKARTA GAMBIR   
1                HONEST SASWITA        17037370.0       11929  JAKARTA GAMBIR   
2                TINI SUHARTINI        19489481.0       11916  JAKARTA GAMBIR   
3                         SANUI        42330985.0       11936  JAKARTA GAMBIR   
4               SOETIRTO TAMZIL        91302562.0       11937  JAKARTA GAMBIR   
...                         ...               ...         ...             ...   
2508           CHANDRA MULIANDI       150000000.0       11931  JAKARTA GAMBIR   
2509             BAMBANG SADONO        23245985.0       11923  JAKARTA GAMBIR   
2510       AVIA HILMANSJAH NOOR        50822983.0       11903  JAKARTA GAMBIR   
2511                  ANTO BARA        25765130.0       11923  JAKARTA GAMBIR   
2512  YOESTANIA PRATAMI HIDAYAT        17512938.0       11900  JAKARTA GAMBIR   

      ureg_status  segment_company_pt  segment_company_owner  
0               1                   0                      0  
1               1                   0                      1  
2               1                   1                      0  
3               1                   1                      0  
4               1                   0                      0  
...           ...                 ...                    ...  
2508            1                   1                      0  
2509            1                   0                      0  
2510            1                   1                      0  
2511            1                   1                      1  
2512            1                   1                      0  

[2006 rows x 10 columns]

In [14]:
data_fix[data_fix['segment_company_owner']==1]

employer_company_name      hp_final   cif_number  \
1                         toko sahabat   owner  6.288200e+11  20001228880   
6                        prima selular pemilik  6.281216e+12   1000154097   
9       sinar lintas khatulistiwa manager exim  6.281399e+12  18002887499   
15                      karya mandiri  pemilik  6.281385e+12  14001085230   
53              pondok pangandran rm   pemilik  6.281219e+12  19004028680   
...                                        ...           ...          ...   
2479                    kens tractor   pemilik  6.281285e+12  19005359043   
2486                 pinnacle system   pemilik  6.281893e+10  18000792833   
2491                   manjaajakarta   pemilik  6.285779e+12  13004075687   
2507                       toko dangan pemilik  6.281277e+12   4000720568   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   

              fullname  indicative_limit  branch_bds          hub_nm  \
1       HONEST SASWITA        17037370.0       11929  JAKARTA GAMBIR   
6      ALFIN KHAIRUDIN        60995619.0       11907  JAKARTA GAMBIR   
9     RATNA KOMALASARI        29991883.0       11929  JAKARTA GAMBIR   
15              NAWAWI        25551024.0       11937  JAKARTA GAMBIR   
53       SURYA WIDJAYA        25100204.0       11929  JAKARTA GAMBIR   
...                ...               ...         ...             ...   
2479           SIE PIN       135305852.0       11912  JAKARTA GAMBIR   
2486    RUDY TANUDARMA        54329097.0       11935  JAKARTA GAMBIR   
2491   MUHAMAD ROZIKIN        38691673.0       11900  JAKARTA GAMBIR   
2507     DANGAN WALUYO        21658650.0       11904  JAKARTA GAMBIR   
2511         ANTO BARA        25765130.0       11923  JAKARTA GAMBIR   

      ureg_status  segment_company_pt  segment_company_owner  
1               1                   0                      1  
6               1                   0                      1  
9               1                   0                      1  
15              1                   0                      1  
53              1                   0                      1  
...           ...                 ...                    ...  
2479            1                   0                      1  
2486            1                   0                      1  
2491            1                   0                      1  
2507            1                   0                      1  
2511            1                   1                      1  

[268 rows x 10 columns]

In [15]:
data_fix[data_fix['employer_company_name']=='perseorangan ibu rumah tangga']

employer_company_name      hp_final   cif_number  \
210  perseorangan ibu rumah tangga  6.281387e+12  13001913584   
236  perseorangan ibu rumah tangga  6.281287e+11  25000385590   

               fullname  indicative_limit  branch_bds          hub_nm  \
210  MASNITA OMPUSUNGGU        19623323.0       11936  JAKARTA GAMBIR   
236               YENTI       150000000.0       11904  JAKARTA GAMBIR   

     ureg_status  segment_company_pt  segment_company_owner  
210            1                   1                      0  
236            1                   1                      0

In [16]:
data_fix['segment_final'] = ''

for index, row in data_fix.iterrows():
    if row['segment_company_pt'] == 1 and row['segment_company_owner'] == 0:
        data_fix.at[index, 'segment_final'] = 1
    elif row['segment_company_pt'] == 0 and row['segment_company_owner'] == 1:
        data_fix.at[index, 'segment_final'] = 2
    elif row['segment_company_pt'] == 0 and row['segment_company_owner'] == 0:
        data_fix.at[index, 'segment_final'] = 3
    else:
        data_fix.at[index, 'segment_final'] = 2

In [17]:
data_fix

employer_company_name      hp_final   cif_number  \
0                         mic mac pelayan toko  6.282268e+12  23001084780   
1                         toko sahabat   owner  6.288200e+11  20001228880   
2        pt  integra line indonesia accounting  6.285715e+12  20001219835   
3       maritime power pt crew pelayaran kapal  6.282184e+12  19005643150   
4                           usaha rental mobil  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        pt  ecom multi solution   it sales  6.282122e+12   3000500265   
2509                       maju lancar mekanik  6.281298e+11   2000851724   
2510                   pt jhonlin marine trans  6.281386e+12   1001899658   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   
2512  kpp pratama jakarta sawah besar satu sek  6.281231e+12  25001737907   

                       fullname  indicative_limit  branch_bds          hub_nm  \
0                 WENDY PRAYOGO        87951727.0       11934  JAKARTA GAMBIR   
1                HONEST SASWITA        17037370.0       11929  JAKARTA GAMBIR   
2                TINI SUHARTINI        19489481.0       11916  JAKARTA GAMBIR   
3                         SANUI        42330985.0       11936  JAKARTA GAMBIR   
4               SOETIRTO TAMZIL        91302562.0       11937  JAKARTA GAMBIR   
...                         ...               ...         ...             ...   
2508           CHANDRA MULIANDI       150000000.0       11931  JAKARTA GAMBIR   
2509             BAMBANG SADONO        23245985.0       11923  JAKARTA GAMBIR   
2510       AVIA HILMANSJAH NOOR        50822983.0       11903  JAKARTA GAMBIR   
2511                  ANTO BARA        25765130.0       11923  JAKARTA GAMBIR   
2512  YOESTANIA PRATAMI HIDAYAT        17512938.0       11900  JAKARTA GAMBIR   

      ureg_status  segment_company_pt  segment_company_owner segment_final  
0               1                   0                      0             3  
1               1                   0                      1             2  
2               1                   1                      0             1  
3               1                   1                      0             1  
4               1                   0                      0             3  
...           ...                 ...                    ...           ...  
2508            1                   1                      0             1  
2509            1                   0                      0             3  
2510            1                   1                      0             1  
2511            1                   1                      1             2  
2512            1                   1                      0             1  

[2006 rows x 11 columns]

In [18]:
data_fix['indicative_limit'].max()

150000000.0

In [19]:
data_fix['flag'] = ''

for index, row in data_fix.iterrows():
    if row['segment_final'] == 3:
        data_fix.at[index, 'flag'] = 1
    elif row['segment_final'] == 2 and row['indicative_limit'] < 30000000:
        data_fix.at[index, 'flag'] = 2
    elif row['segment_final'] == 2 and row['indicative_limit'] >= 30000000:
        data_fix.at[index, 'flag'] = 3
    elif row['segment_final'] == 1:
        data_fix.at[index, 'flag'] = 4
data_fix

employer_company_name      hp_final   cif_number  \
0                         mic mac pelayan toko  6.282268e+12  23001084780   
1                         toko sahabat   owner  6.288200e+11  20001228880   
2        pt  integra line indonesia accounting  6.285715e+12  20001219835   
3       maritime power pt crew pelayaran kapal  6.282184e+12  19005643150   
4                           usaha rental mobil  6.281851e+10  19003595498   
...                                        ...           ...          ...   
2508        pt  ecom multi solution   it sales  6.282122e+12   3000500265   
2509                       maju lancar mekanik  6.281298e+11   2000851724   
2510                   pt jhonlin marine trans  6.281386e+12   1001899658   
2511  pt metropolitan land manager engineering  6.281282e+12   1001771517   
2512  kpp pratama jakarta sawah besar satu sek  6.281231e+12  25001737907   

                       fullname  indicative_limit  branch_bds          hub_nm  \
0                 WENDY PRAYOGO        87951727.0       11934  JAKARTA GAMBIR   
1                HONEST SASWITA        17037370.0       11929  JAKARTA GAMBIR   
2                TINI SUHARTINI        19489481.0       11916  JAKARTA GAMBIR   
3                         SANUI        42330985.0       11936  JAKARTA GAMBIR   
4               SOETIRTO TAMZIL        91302562.0       11937  JAKARTA GAMBIR   
...                         ...               ...         ...             ...   
2508           CHANDRA MULIANDI       150000000.0       11931  JAKARTA GAMBIR   
2509             BAMBANG SADONO        23245985.0       11923  JAKARTA GAMBIR   
2510       AVIA HILMANSJAH NOOR        50822983.0       11903  JAKARTA GAMBIR   
2511                  ANTO BARA        25765130.0       11923  JAKARTA GAMBIR   
2512  YOESTANIA PRATAMI HIDAYAT        17512938.0       11900  JAKARTA GAMBIR   

      ureg_status  segment_company_pt  segment_company_owner segment_final  \
0               1                   0                      0             3   
1               1                   0                      1             2   
2               1                   1                      0             1   
3               1                   1                      0             1   
4               1                   0                      0             3   
...           ...                 ...                    ...           ...   
2508            1                   1                      0             1   
2509            1                   0                      0             3   
2510            1                   1                      0             1   
2511            1                   1                      1             2   
2512            1                   1                      0             1   

     flag  
0       1  
1       2  
2       4  
3       4  
4       1  
...   ...  
2508    4  
2509    1  
2510    4  
2511    2  
2512    4  

[2006 rows x 12 columns]

In [20]:
data_fix['flag'] = data_fix['flag'].astype('int32')
data_fix['segment_final'] = data_fix['segment_final'].astype('int32')
data_fix.dtypes

employer_company_name     object
hp_final                 float64
cif_number                 int64
fullname                  object
indicative_limit         float64
branch_bds                 int64
hub_nm                    object
ureg_status                int64
segment_company_pt         int32
segment_company_owner      int32
segment_final              int32
flag                       int32
dtype: object

In [21]:
X = data_fix[['segment_final','indicative_limit']]
X

segment_final  indicative_limit
0                 3        87951727.0
1                 2        17037370.0
2                 1        19489481.0
3                 1        42330985.0
4                 3        91302562.0
...             ...               ...
2508              1       150000000.0
2509              3        23245985.0
2510              1        50822983.0
2511              2        25765130.0
2512              1        17512938.0

[2006 rows x 2 columns]

In [22]:
y = data_fix['flag']
y

0       1
1       2
2       4
3       4
4       1
       ..
2508    4
2509    1
2510    4
2511    2
2512    4
Name: flag, Length: 2006, dtype: int32

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

In [24]:
# Create function to evaluate our model
def classification_eval (aktual, prediksi, name):
    cm = confusion_matrix(aktual, prediksi)
    tp = cm[1][1]
    tn = cm[0][0]
    fp = cm[0][1]
    fn = cm[1][0]
    
    accuracy = round((tp+tn) / (tp+tn+fp+fn) * 100, 2)
    precision = round((tp) / (tp+fp) * 100, 2)
    recall = round((tp) / (tp+fn) * 100, 2)
    specificity = round((tn) / (tn+fp) * 100, 2)
    
    print('Evaluation Model:', name)
    print(cm)
    print('Accuracy   :', accuracy, '%')
    print('Precision  :', precision, '%')
    print('Recall     :', recall, '%')
    print('Specificity:', specificity, '%')

In [25]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_train_pred = knn.predict(X_train)
y_test_pred = knn.predict(X_test)
classification_eval(y_train, y_train_pred, 'KNN Training Perf.')

Evaluation Model: KNN Training Perf.
[[175   5  14 191]
 [  7  21   0  40]
 [ 32   0  53  53]
 [ 88  22  19 884]]
Accuracy   : 94.23 %
Precision  : 80.77 %
Recall     : 75.0 %
Specificity: 97.22 %


In [26]:
classification_eval(y_test, y_test_pred, 'KNN Testing Perf.')

Evaluation Model: KNN Testing Perf.
[[ 37   7   6  74]
 [  1   1   0  17]
 [ 11   0  13  19]
 [ 31   5   8 172]]
Accuracy   : 82.61 %
Precision  : 12.5 %
Recall     : 50.0 %
Specificity: 84.09 %


In [27]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_train_pred = dt.predict(X_train)
y_test_pred = dt.predict(X_test)
classification_eval(y_train, y_train_pred, 'Dectree Training Perf.')

Evaluation Model: Dectree Training Perf.
[[ 385    0    0    0]
 [   0   68    0    0]
 [   0    0  138    0]
 [   0    0    0 1013]]
Accuracy   : 100.0 %
Precision  : 100.0 %
Recall     : 100.0 %
Specificity: 100.0 %


In [28]:
classification_eval(y_test, y_test_pred, 'Dectree Testing Perf.')

Evaluation Model: Dectree Testing Perf.
[[124   0   0   0]
 [  0  19   0   0]
 [  0   0  43   0]
 [  0   0   0 216]]
Accuracy   : 100.0 %
Precision  : 100.0 %
Recall     : 100.0 %
Specificity: 100.0 %


In [29]:
rf = RandomForestClassifier(random_state = 123)
rf.fit(X_train, y_train)
y_train_pred = rf.predict(X_train)
y_test_pred = rf.predict(X_test)
classification_eval(y_train, y_train_pred, 'Ranfor Training Perf.')

Evaluation Model: Ranfor Training Perf.
[[ 385    0    0    0]
 [   0   68    0    0]
 [   0    0  138    0]
 [   0    0    0 1013]]
Accuracy   : 100.0 %
Precision  : 100.0 %
Recall     : 100.0 %
Specificity: 100.0 %


In [30]:
classification_eval(y_test, y_test_pred, 'Ranfor Testing Perf.')

Evaluation Model: Ranfor Testing Perf.
[[124   0   0   0]
 [  0  19   0   0]
 [  0   0  43   0]
 [  0   0   0 216]]
Accuracy   : 100.0 %
Precision  : 100.0 %
Recall     : 100.0 %
Specificity: 100.0 %


In [31]:
data_test = pd.read_excel('Data_test.xlsx')
data_test['indicative_limit'] = data_test['indicative_limit'].astype('float64')
data_test['segment_final'] = data_test['segment_final'].astype('int32')
data_test

segment_final  indicative_limit
0               2        18759485.0
1               1         5496600.0
2               3        69400075.0
3               3        85490067.0
4               1        54809074.0
5               2         7894456.0
6               3       170000000.0
7               1        64587223.0
8               2        16879408.0
9               1        75400689.0
10              2        35000000.0

In [32]:
data_test_subset_rf = data_test[['segment_final', 'indicative_limit']]
data_test_subset_dt = data_test[['segment_final', 'indicative_limit']]
data_test_subset_knn = data_test[['segment_final', 'indicative_limit']]

data_test_subset_rf['prediction_rf'] = rf.predict(data_test_subset_rf)
data_test_subset_rf

segment_final  indicative_limit  prediction_rf
0               2        18759485.0              2
1               1         5496600.0              4
2               3        69400075.0              1
3               3        85490067.0              1
4               1        54809074.0              4
5               2         7894456.0              2
6               3       170000000.0              1
7               1        64587223.0              4
8               2        16879408.0              2
9               1        75400689.0              4
10              2        35000000.0              3

In [33]:
data_test_subset_dt['prediction_dt'] = dt.predict(data_test_subset_dt)
data_test_subset_dt

segment_final  indicative_limit  prediction_dt
0               2        18759485.0              2
1               1         5496600.0              4
2               3        69400075.0              1
3               3        85490067.0              1
4               1        54809074.0              4
5               2         7894456.0              2
6               3       170000000.0              1
7               1        64587223.0              4
8               2        16879408.0              2
9               1        75400689.0              4
10              2        35000000.0              3

In [34]:
data_test_subset_knn['prediction_knn'] = knn.predict(data_test_subset_knn)
data_test_subset_knn

segment_final  indicative_limit  prediction_knn
0               2        18759485.0               4
1               1         5496600.0               4
2               3        69400075.0               4
3               3        85490067.0               4
4               1        54809074.0               4
5               2         7894456.0               4
6               3       170000000.0               1
7               1        64587223.0               1
8               2        16879408.0               4
9               1        75400689.0               1
10              2        35000000.0               1

In [35]:
pickle.dump(dt, open('dt.pkl', 'wb'))